version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: backend-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: nestjs_app
      POSTGRES_USER: nestjs_user
      POSTGRES_PASSWORD: nestjs_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U nestjs_user -d nestjs_app"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local 